### ISSUE TITLE
Good Job !-- Have query

### ISSUE THREAD

**Issue by jaideep11061982** [LaurentVeyssier/Minimize-Energy-consumption-with-Deep-Learning-model#1]
@LaurentVeyssier 
from where did we get the desired environment data ?
How to fit our environment to this ?

**Comment by LaurentVeyssier** [comment]
Hello Jaideep, the project is part of Udemy' s Artificial Intelligence for Business course. I covered it a while back and I do not remember a dataset. Have you checked that the data is not synthetically built in the code?
otherwise I suggest you go for the Udemy materials. there is a couple of other biz case of interest.
